version: '3.8'
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: db_services
    ports:
      - 5432:5432
    working_dir: "/src"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./src/:/src/
volumes:
  dbdata: {}
